BriBett/BriBett/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.contrib import admin
from django.conf import settings
from BrianWeb import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'BriBettTech/', include('BrianWeb.urls'))
]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

BriBett/BrianWeb/urls.py
from django.conf.urls import url
from . import views

app_name = 'BrianWeb'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about', views.about, name='about'),
    url(r'^portfolio', views.portfolio, name='portfolio'),
    url(r'^contact', views.contact, name='contact')
]

BriBett/BrianWeb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class User(models.Model):
    user_id = models.CharField(max_length=100, unique=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return self.last_name

class Projects(models.Model):
    project_id = models.CharField(max_length=100, unique=True)
    project_title = models.CharField(max_length=200)
    project_image = models.ImageField(upload_to='projects')
    project_description = models.TextField(max_length=2500)

    def __str__(self):
        return self.project_title

class UpdateInfo(models.Model):
    project_id = models.ForeignKey(Projects, on_delete= models.CASCADE)
    date_modified = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.project_id)

BriBett/BrianWeb/forms.py
from django import forms

class SubscriptionForm(forms.Form):
    email_address = forms.EmailField(label="Enter Your Email ", max_length=200)

BriBett/BrianWeb/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Projects, User, UpdateInfo
from .forms import SubscriptionForm

# Create your views here.

def index(request):
    return render(request, 'BrianWeb/index.html')

def about(request):
    return render(request, 'BrianWeb/about.html')

def portfolio(request):
    portfolio = Projects.objects.all()
    #update_info = UpdateInfo.objects.all()
    user_info = User.objects.all()

    portfolio_dict = {
        'portfolio': portfolio,
        'user': user_info,
    }

    return render(request, 'BrianWeb/portfolio.html', context=portfolio_dict)

def contact(request):
    form = SubscriptionForm()
    return render(request, 'BrianWeb/contact.html', {'form' : form})

BriBett/templates/BrianWeb/about.html
<!DOCTYPE html>
{% extends "BrianWeb/base.html"%}
{% load static %}

{% block body_block%}

  <section class="container-fluid" id="about-head">
    <div class="welcome welcome-about">
      <h1 class="text-left welcome-header">About BriBett Technologies</h1>
    </div>
    <div class="message text-left">
        <p>Get to Know BriBett</p>
    </div>
  </section>

  <section class="container-fluid" id="services">
    <div class="services-head">
      <h3 class="text-center">Services We Provide</h3>
    </div>
    <div class="line">
      <hr>
    </div>
    <div class="row">
      <div class="container col-md-4 col-sm-12 " id="services-web">
        <div class="web-image">
          <img src="" alt="">
        </div>
        <div class="web-header">
          <h4 class="text-center">Web App. Development</h4>
        </div>
        <div class="row web-content">
          <div class="col-lg-4 col-md-4 col-sm-6">
            <img src="{% static 'images/webDevelop1.png' %}" height="150px" width="150px">
          </div>
          <div class="col-lg-8 col-md-8 col-sm-6">
            <p class="text-center">
              BriBett seeks develop websites and web systems that will make
              your dreams come true and be visible and made possible at any
              part of the world
            </p>
          </div>
        </div>
      </div>
      <div class="container col-md-4 col-sm-12" id="services-desktop">
        <div class="desktop-image">
          <img src="" alt="">
        </div>
        <div class="desktop-header">
          <h4 class="text-center">Desktop App. Development</h4>
        </div>
        <div class="row desktop-content">
          <div class="col-lg-4 col-md-4 col-sm-6">
            <img src="{% static 'images/deskApp.png' %}" height="150px" width="150px">
          </div>
          <div class="col-lg-8 col-md-8 col-sm-6">
            <p class="text-center">
              BriBett seeks develop websites and web systems that will make
              your dreams come true and be visible and made possible at any
              part of the world
            </p>
          </div>
        </div>
      </div>
      <div class="container col-md-4 col-sm-12" id="services-mobile">
        <div class="mobile-image">
          <img src="" alt="">
        </div>
        <div class="mobile-header">
          <h4 class="text-center">Mobile App. Development</h4>
        </div>
        <div class=" row mobile-content">
          <div class="col-lg-4 col-md-4 col-sm-6">
            <img src="{% static 'images/services_mobile-development.png' %}" height="150px" width="150px">
          </div>
          <div class="col-lg-8 col-md-8 col-sm-6">
            <p class="text-center">
              BriBett seeks develop websites and web systems that will make
              your dreams come true and be visible and made possible at any
              part of the world
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <hr>
  <section class="container-fluid">
    <div class="row container">
      <div class="col-md-6 col-sm-12 aim">
        <div class="row">
          <div class="col-md-4 col-sm-12 objective-head">
            <h5>AIM</h5>
          </div>
          <div class="col-md-8 col-sm-12 objective-content">
            <p>
              BriBett seeks develop websites and web systems that will make
            your dreams come true and be visible and made possible at any
            part of the world
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-sm-12 objective">
        <div class="row">
          <div class="col-md-4 col-sm-12 objective-head">
            <h5>OBJECTIVE</h5>
          </div>
          <div class="col-md-8 col-sm-12 objective-content">
            <p>
              BriBett seeks develop websites and web systems that will make
            your dreams come true and be visible and made possible at any
            part of the world
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

BriBett/templates/BrianWeb/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>BriBett Technologies</title>
    <link rel='icon' href='{% static "images/favicon.ico" %}' type='image/x-icon'>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light navbar-fixed-top">
        <div class="navbar-header">
          <a href="{% url 'BrianWeb:index' %}" class="navbar-brand">BriBett Technologies</a>
        </div>
        <button type="button" name="button" class="navbar-toggler bg-dark" data-toggle="collapse" data-target="#bribett" aria-controls="navbarSupportedContents" aria-expanded="false">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="bribett">
          <ul class="navbar-nav">
            <li class="nav-item"><a href="{% url 'BrianWeb:index' %}" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="{% url 'BrianWeb:about' %}" class="nav-link">About Us</a></li>
            <li class="nav-item"><a href="{% url 'BrianWeb:portfolio' %}" class="nav-link">Portfolio</a></li>
            <li class="nav-item"><a href="{% url 'BrianWeb:contact' %}" class="nav-link">Contact Us</a></li>
          </ul>
        </div>
      </nav>
    </div>
    <div class="container-fluid">
      {% block body_block %}

      {% endblock%}
    </div>
    <section class="footer">
      <div class="container-fluid bg-dark">
        <div class="container">
          <div class="row">
            <div class="col-lg-4, col-md-4 col-sm-12">
              <nav class="navbar">
                <div class="nav-brand" id="footer-brand">
                  BriBett Technologies
                </div>
              </nav>
            </div>

            <div class="col-lg-4, col-md-4 col-sm-12">
              <nav class="navbar">
                <ul class="navbar-nav social">
                  <li><a target="_blank" href="#" class="nav-link"><span class="fa fa-facebook text-lg"></span></a></li>
                  <li><a target="_blank" href="#" class="nav-link"><span class="fa fa-twitter text-lg"></span></a></li>
                </ul>
              </nav>
            </div>

            <div class="col-lg-4, col-md-4 col-sm-12">
              <div class="text-center">
                &copy BriBett2020
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

BriBett/templates/BrianWeb/contact.html
<!DOCTYPE html>
{% extends "BrianWeb/base.html"%}
{% load static %}

{% block body_block%}
    <section class="container-fluid" id="contact-head">
        <div class="welcome welcome-contact text-left">
          <h1 class="welcome-header">contact BriBett</h1>
        </div>
        <div class="message text-left">
            <p>Get In Touch With BriBett</p>
        </div>
    </section>

    <section class="container-fluid" id="contacts">
      <div>
          <h3 class="text-center reason-header">Our Contacts & Location</h3>
      </div>
      <div class="line">
        <hr>
      </div>
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12">
          <div class="contacts text-center">
            <p><span class="fa fa-envelope"></span> :<a href="mailto:bribett@gmail.com">bribett@gmail.com</a></p>
            <p><span class="fa fa-phone"></span> : +254700403306 </p>
            <p><span class=""></span></p>
          </div>
        </div>
        <div class="map">
          <map>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d31918.01009300513!2d35.308383199999994!3d-0.3321921!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x3ece3c5f923d46d7!2sSumeiyon%20Primary%20School!5e0!3m2!1sen!2ske!4v1582634322589!5m2!1sen!2ske" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen=""></iframe>
        </div>
      </div>
    </section>

    <section class="container-fluid" id="subscribe">
      <div class="form">
        <form  method="POST">
          <div class="form-group">
              {{ form.as_table }}
            {% csrf_token %}
            <input type="submit" name="subscribe" value="Subscribe" class="btn btn-info">
          </div>
        </form>
      </div>
    </section>
{% endblock %}

BriBett/templates/BrianWeb/index.html
<!DOCTYPE html>
{% extends "BrianWeb/base.html"%}
{% load static %}

{% block body_block%}
<div>
    <section class="container-fluid" id="index-head">
        <div class="welcome welcome-home text-left container-fluid">
            <h1 class="welcome-header">BriBett Technologies</h1>
        </div>
        <div class="message text-left">
            <p>Welcome to BriBett</p>
        </div>
    </section>

    <section class="container-fluid" id="reason">
        <div>
            <h3 class="text-center reason-header">Why BriBett?</h3>
        </div>
        <div class="line">
          <hr>
        </div>
        <div class="row">
           <div class="container col-lg 6 col-md-6 col-sm-12 reasons">
               <div class="reason-head">
                   <h5 class="text-center">Build A Better Digital World for You</h5>
               </div>
               <div class="reason-body container">
                   <span class="fa fa-globe"></span>
                   <p class="text-center">
                       BriBett seeks to be one of the best web, desktop and mobile application developers that will make
                       your dreams come true
                   </p>
               </div>
           </div>
           <div class="container col-lg 6 col-md-6 col-sm-12">
               <div class="container col-lg 6 col-md-6 col-sm-12">
                   <div class="reason-head">
                       <h5 class="text-center">Be Part of The Elite</h5>
                   </div>
                   <div class="reason-body container">
                       <span class="fa fa-globe"></span>
                       <p class="text-center">
                           Get to be part of the clients with the most elite and customer user friendly applications
                           that will take your business and ideas to the next level.
                       </p>
                   </div>
               </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}

BriBett/templates/BrianWeb/portfolio.html
<!DOCTYPE html>
{% extends "BrianWeb/base.html"%}
{% load static %}

{% block body_block%}

  <section class="container-fluid" id="portfolio-head">
    <div class="welcome welcome-portfolio text-left">
      <h1 class="welcome-header">work done at BriBett</h1>
    </div>
    <div class="message text-left">
        <p>Get A Test Of the Best Applications</p>
    </div>
  </section>

  <section class="container-fluid">
    <div class="text-center">
      <h3>Projects Done</h3>
    </div>
    <div class="line">
      <hr>
    </div>
    <div class="row">
      {% for port in portfolio %}
        {% for users in user %}
          <div class="col-lg-4 col-md-4 col-sm-12">
            <div class="title">
              <h3 class="text-center">{{ port.portfolio_title }}</h3>
            </div>
            <div class="project_image">
              <img src="{{ port.project_image.url }}" height="200px" width="100%">
            </div>
            <div class="project-auther">
              <p>Project done by {{ users.user }}</p>
            </div>
            <div class="project-description">
              <p>{{ port.project_description }}</p>
            </div>
          </div>
        {% endfor %}
      {% endfor %}
    </div>
  </section>
{% endblock %}